{1:F01BPIRRUMMAXXX0000000000}{2:I999#swift_name#N}{4:
:20:#refer# 
:79:WE CONFIRM LENDING FUNDS IN DEPOSIT WIHT YOU
CURRENCY: #CUR#
PRINCIPAL AMOUNT: #CUR# #AMOUNT#
INTEREST RATE: #Rate# PCT
INTEREST AMOUNT: #Proc_AMOUNT#
TRADE DATE: #Trade_Date#
VALUE DATE: #Value_Date#
MATURITY DATE: #Maturity_Date#
FULL MOVEMENT: #AMOUNT#
WHITHOUT MOVEMENT: 0.00
ARRANGED BY: PHONE
GENERAL AGREEMENT N #Gen_Sogl# FROM #Gen_Sogl_date#
CREDIT AGREEMENT N #cont-code# FROM #DateSogl#
SUPPLEMENTARY AGREEMENT N #transh_number#
OUR PAYMENT:
ACCORDING YOUR INSTRUCTIONS

YOUR PAYMENT
/30101810500000000491
 WITH PIR BANK, LLC., MOSCOW          	
 BIC 044585491, INN 7708031739,
#PAYMENTS#

IN CASE OF ANY DISCREPANCY PLEASE DO NOT HESITATE 
TO CONTACT US

BEST REGARDS,
PIR BANK, LLC.
+7 (495) 755 61 41
-}
                        
