//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageServiceUsageExample.MessageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageServiceReference.IMessageService")]
    public interface IMessageService {
        
        // CODEGEN: Parameter 'endDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessageIds", ReplyAction="http://tempuri.org/IMessageService/GetMessageIdsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse GetMessageIds(MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessageIds", ReplyAction="http://tempuri.org/IMessageService/GetMessageIdsResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse> GetMessageIdsAsync(MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessageContent", ReplyAction="http://tempuri.org/IMessageService/GetMessageContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMessageContent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessageContent", ReplyAction="http://tempuri.org/IMessageService/GetMessageContentResponse")]
        System.Threading.Tasks.Task<string> GetMessageContentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessageContent", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessageContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTradeMessageContent(int idTradeMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessageContent", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessageContentResponse")]
        System.Threading.Tasks.Task<string> GetTradeMessageContentAsync(int idTradeMessage);
        
        // CODEGEN: Parameter 'endTo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessages", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse GetTradeMessages(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessages", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessagesResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse> GetTradeMessagesAsync(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest request);
        
        // CODEGEN: Parameter 'endTo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessagesByTrade", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessagesByTradeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse GetTradeMessagesByTrade(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetTradeMessagesByTrade", ReplyAction="http://tempuri.org/IMessageService/GetTradeMessagesByTradeResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse> GetTradeMessagesByTradeAsync(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest request);
        
        // CODEGEN: Parameter 'date' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetArbitrManagerRegister", ReplyAction="http://tempuri.org/IMessageService/GetArbitrManagerRegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse GetArbitrManagerRegister(MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetArbitrManagerRegister", ReplyAction="http://tempuri.org/IMessageService/GetArbitrManagerRegisterResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse> GetArbitrManagerRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest request);
        
        // CODEGEN: Parameter 'date' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetDebtorRegister", ReplyAction="http://tempuri.org/IMessageService/GetDebtorRegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse GetDebtorRegister(MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetDebtorRegister", ReplyAction="http://tempuri.org/IMessageService/GetDebtorRegisterResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse> GetDebtorRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest request);
        
        // CODEGEN: Parameter 'date' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetCompanyTradeOrganizerRegister", ReplyAction="http://tempuri.org/IMessageService/GetCompanyTradeOrganizerRegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse GetCompanyTradeOrganizerRegister(MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetCompanyTradeOrganizerRegister", ReplyAction="http://tempuri.org/IMessageService/GetCompanyTradeOrganizerRegisterResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse> GetCompanyTradeOrganizerRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest request);
        
        // CODEGEN: Parameter 'date' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetSroRegister", ReplyAction="http://tempuri.org/IMessageService/GetSroRegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DebtorRegisterItem))]
        MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse GetSroRegister(MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetSroRegister", ReplyAction="http://tempuri.org/IMessageService/GetSroRegisterResponse")]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse> GetSroRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageIds", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endDate;
        
        public GetMessageIdsRequest() {
        }
        
        public GetMessageIdsRequest(System.DateTime startDate, System.Nullable<System.DateTime> endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageIdsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetMessageIdsResult;
        
        public GetMessageIdsResponse() {
        }
        
        public GetMessageIdsResponse(int[] GetMessageIdsResult) {
            this.GetMessageIdsResult = GetMessageIdsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TradePlace : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Trade[] tradeListField;
        
        private string iNNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Trade[] TradeList {
            get {
                return this.tradeListField;
            }
            set {
                this.tradeListField = value;
                this.RaisePropertyChanged("TradeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Trade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TradeMessage[] messageListField;
        
        private string iD_ExternalField;
        
        private int iD_EFRSBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public TradeMessage[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("MessageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID_External {
            get {
                return this.iD_ExternalField;
            }
            set {
                this.iD_ExternalField = value;
                this.RaisePropertyChanged("ID_External");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID_EFRSB {
            get {
                return this.iD_EFRSBField;
            }
            set {
                this.iD_EFRSBField = value;
                this.RaisePropertyChanged("ID_EFRSB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TradeMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuInn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iNNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SroRegisterItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuInn[] auListField;
        
        private string fullNameField;
        
        private string regNumField;
        
        private System.DateTime dateRegField;
        
        private string iNNField;
        
        private string urAdressField;
        
        private string phoneField;
        
        private System.DateTime dateExcludeField;
        
        private bool dateExcludeFieldSpecified;
        
        private string causeExcludeField;
        
        private System.DateTime dateLastModifField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Au")]
        public AuInn[] AuList {
            get {
                return this.auListField;
            }
            set {
                this.auListField = value;
                this.RaisePropertyChanged("AuList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegNum {
            get {
                return this.regNumField;
            }
            set {
                this.regNumField = value;
                this.RaisePropertyChanged("RegNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateReg {
            get {
                return this.dateRegField;
            }
            set {
                this.dateRegField = value;
                this.RaisePropertyChanged("DateReg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrAdress {
            get {
                return this.urAdressField;
            }
            set {
                this.urAdressField = value;
                this.RaisePropertyChanged("UrAdress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateExclude {
            get {
                return this.dateExcludeField;
            }
            set {
                this.dateExcludeField = value;
                this.RaisePropertyChanged("DateExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateExcludeSpecified {
            get {
                return this.dateExcludeFieldSpecified;
            }
            set {
                this.dateExcludeFieldSpecified = value;
                this.RaisePropertyChanged("DateExcludeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CauseExclude {
            get {
                return this.causeExcludeField;
            }
            set {
                this.causeExcludeField = value;
                this.RaisePropertyChanged("CauseExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateLastModif {
            get {
                return this.dateLastModifField;
            }
            set {
                this.dateLastModifField = value;
                this.RaisePropertyChanged("DateLastModif");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SROList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SroRegisterItem[] sROList1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("SROList", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SRO")]
        public SroRegisterItem[] SROList1 {
            get {
                return this.sROList1Field;
            }
            set {
                this.sROList1Field = value;
                this.RaisePropertyChanged("SROList1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyTradeOrganizerRegisterItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private string shortNameField;
        
        private string iNNField;
        
        private string oGRNField;
        
        private System.DateTime dateLastModifField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OGRN {
            get {
                return this.oGRNField;
            }
            set {
                this.oGRNField = value;
                this.RaisePropertyChanged("OGRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateLastModif {
            get {
                return this.dateLastModifField;
            }
            set {
                this.dateLastModifField = value;
                this.RaisePropertyChanged("DateLastModif");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TradeOrganizerList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompanyTradeOrganizerRegisterItem[] tradeOrganizerList1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("TradeOrganizerList", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TradeOrganizer")]
        public CompanyTradeOrganizerRegisterItem[] TradeOrganizerList1 {
            get {
                return this.tradeOrganizerList1Field;
            }
            set {
                this.tradeOrganizerList1Field = value;
                this.RaisePropertyChanged("TradeOrganizerList1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyDebtorRegisterItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonDebtorRegisterItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class DebtorRegisterItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyDebtorRegisterItem : DebtorRegisterItem {
        
        private string fullNameField;
        
        private string shortNameField;
        
        private string iNNField;
        
        private string oGRNField;
        
        private System.DateTime dateLastModifField;
        
        private string regionField;
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OGRN {
            get {
                return this.oGRNField;
            }
            set {
                this.oGRNField = value;
                this.RaisePropertyChanged("OGRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateLastModif {
            get {
                return this.dateLastModifField;
            }
            set {
                this.dateLastModifField = value;
                this.RaisePropertyChanged("DateLastModif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonDebtorRegisterItem : DebtorRegisterItem {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string iNNField;
        
        private System.DateTime dateLastModifField;
        
        private string regionField;
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateLastModif {
            get {
                return this.dateLastModifField;
            }
            set {
                this.dateLastModifField = value;
                this.RaisePropertyChanged("DateLastModif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DebtorList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DebtorRegisterItem[] debtorList1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("DebtorList", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DebtorCompany", typeof(CompanyDebtorRegisterItem))]
        [System.Xml.Serialization.XmlArrayItemAttribute("DebtorPerson", typeof(PersonDebtorRegisterItem))]
        public DebtorRegisterItem[] DebtorList1 {
            get {
                return this.debtorList1Field;
            }
            set {
                this.debtorList1Field = value;
                this.RaisePropertyChanged("DebtorList1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArbitrManagerRegisterItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string regNumField;
        
        private string iNNField;
        
        private string sRORegNumField;
        
        private System.DateTime dateLastModifField;
        
        private string regionField;
        
        private System.DateTime dateRegField;
        
        private bool dateRegFieldSpecified;
        
        private System.DateTime sRORegDateField;
        
        private bool sRORegDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegNum {
            get {
                return this.regNumField;
            }
            set {
                this.regNumField = value;
                this.RaisePropertyChanged("RegNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SRORegNum {
            get {
                return this.sRORegNumField;
            }
            set {
                this.sRORegNumField = value;
                this.RaisePropertyChanged("SRORegNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateLastModif {
            get {
                return this.dateLastModifField;
            }
            set {
                this.dateLastModifField = value;
                this.RaisePropertyChanged("DateLastModif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateReg {
            get {
                return this.dateRegField;
            }
            set {
                this.dateRegField = value;
                this.RaisePropertyChanged("DateReg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateRegSpecified {
            get {
                return this.dateRegFieldSpecified;
            }
            set {
                this.dateRegFieldSpecified = value;
                this.RaisePropertyChanged("DateRegSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime SRORegDate {
            get {
                return this.sRORegDateField;
            }
            set {
                this.sRORegDateField = value;
                this.RaisePropertyChanged("SRORegDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SRORegDateSpecified {
            get {
                return this.sRORegDateFieldSpecified;
            }
            set {
                this.sRORegDateFieldSpecified = value;
                this.RaisePropertyChanged("SRORegDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArbitrManagerRegisterItem[] aMList1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("AMList", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArbitrManager")]
        public ArbitrManagerRegisterItem[] AMList1 {
            get {
                return this.aMList1Field;
            }
            set {
                this.aMList1Field = value;
                this.RaisePropertyChanged("AMList1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTradeMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTradeMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime startFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endTo;
        
        public GetTradeMessagesRequest() {
        }
        
        public GetTradeMessagesRequest(System.DateTime startFrom, System.Nullable<System.DateTime> endTo) {
            this.startFrom = startFrom;
            this.endTo = endTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTradeMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTradeMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessagesResult;
        
        public GetTradeMessagesResponse() {
        }
        
        public GetTradeMessagesResponse(MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessagesResult) {
            this.GetTradeMessagesResult = GetTradeMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTradeMessagesByTrade", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTradeMessagesByTradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime startFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string tradePlaceInn;
        
        public GetTradeMessagesByTradeRequest() {
        }
        
        public GetTradeMessagesByTradeRequest(System.DateTime startFrom, System.Nullable<System.DateTime> endTo, string id, string tradePlaceInn) {
            this.startFrom = startFrom;
            this.endTo = endTo;
            this.id = id;
            this.tradePlaceInn = tradePlaceInn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTradeMessagesByTradeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTradeMessagesByTradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessagesByTradeResult;
        
        public GetTradeMessagesByTradeResponse() {
        }
        
        public GetTradeMessagesByTradeResponse(MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessagesByTradeResult) {
            this.GetTradeMessagesByTradeResult = GetTradeMessagesByTradeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArbitrManagerRegister", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArbitrManagerRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date;
        
        public GetArbitrManagerRegisterRequest() {
        }
        
        public GetArbitrManagerRegisterRequest(System.Nullable<System.DateTime> date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArbitrManagerRegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArbitrManagerRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.AMList GetArbitrManagerRegisterResult;
        
        public GetArbitrManagerRegisterResponse() {
        }
        
        public GetArbitrManagerRegisterResponse(MessageServiceUsageExample.MessageServiceReference.AMList GetArbitrManagerRegisterResult) {
            this.GetArbitrManagerRegisterResult = GetArbitrManagerRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDebtorRegister", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDebtorRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date;
        
        public GetDebtorRegisterRequest() {
        }
        
        public GetDebtorRegisterRequest(System.Nullable<System.DateTime> date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDebtorRegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDebtorRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.DebtorList GetDebtorRegisterResult;
        
        public GetDebtorRegisterResponse() {
        }
        
        public GetDebtorRegisterResponse(MessageServiceUsageExample.MessageServiceReference.DebtorList GetDebtorRegisterResult) {
            this.GetDebtorRegisterResult = GetDebtorRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyTradeOrganizerRegister", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCompanyTradeOrganizerRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date;
        
        public GetCompanyTradeOrganizerRegisterRequest() {
        }
        
        public GetCompanyTradeOrganizerRegisterRequest(System.Nullable<System.DateTime> date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyTradeOrganizerRegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCompanyTradeOrganizerRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.TradeOrganizerList GetCompanyTradeOrganizerRegisterResult;
        
        public GetCompanyTradeOrganizerRegisterResponse() {
        }
        
        public GetCompanyTradeOrganizerRegisterResponse(MessageServiceUsageExample.MessageServiceReference.TradeOrganizerList GetCompanyTradeOrganizerRegisterResult) {
            this.GetCompanyTradeOrganizerRegisterResult = GetCompanyTradeOrganizerRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSroRegister", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSroRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date;
        
        public GetSroRegisterRequest() {
        }
        
        public GetSroRegisterRequest(System.Nullable<System.DateTime> date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSroRegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSroRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MessageServiceUsageExample.MessageServiceReference.SROList GetSroRegisterResult;
        
        public GetSroRegisterResponse() {
        }
        
        public GetSroRegisterResponse(MessageServiceUsageExample.MessageServiceReference.SROList GetSroRegisterResult) {
            this.GetSroRegisterResult = GetSroRegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : MessageServiceUsageExample.MessageServiceReference.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<MessageServiceUsageExample.MessageServiceReference.IMessageService>, MessageServiceUsageExample.MessageServiceReference.IMessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetMessageIds(MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest request) {
            return base.Channel.GetMessageIds(request);
        }
        
        public int[] GetMessageIds(System.DateTime startDate, System.Nullable<System.DateTime> endDate) {
            MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetMessageIds(inValue);
            return retVal.GetMessageIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetMessageIdsAsync(MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest request) {
            return base.Channel.GetMessageIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetMessageIdsResponse> GetMessageIdsAsync(System.DateTime startDate, System.Nullable<System.DateTime> endDate) {
            MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetMessageIdsRequest();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetMessageIdsAsync(inValue);
        }
        
        public string GetMessageContent(int id) {
            return base.Channel.GetMessageContent(id);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageContentAsync(int id) {
            return base.Channel.GetMessageContentAsync(id);
        }
        
        public string GetTradeMessageContent(int idTradeMessage) {
            return base.Channel.GetTradeMessageContent(idTradeMessage);
        }
        
        public System.Threading.Tasks.Task<string> GetTradeMessageContentAsync(int idTradeMessage) {
            return base.Channel.GetTradeMessageContentAsync(idTradeMessage);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetTradeMessages(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest request) {
            return base.Channel.GetTradeMessages(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessages(System.DateTime startFrom, System.Nullable<System.DateTime> endTo) {
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest();
            inValue.startFrom = startFrom;
            inValue.endTo = endTo;
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetTradeMessages(inValue);
            return retVal.GetTradeMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetTradeMessagesAsync(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest request) {
            return base.Channel.GetTradeMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesResponse> GetTradeMessagesAsync(System.DateTime startFrom, System.Nullable<System.DateTime> endTo) {
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesRequest();
            inValue.startFrom = startFrom;
            inValue.endTo = endTo;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetTradeMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetTradeMessagesByTrade(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest request) {
            return base.Channel.GetTradeMessagesByTrade(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.TradePlace[] GetTradeMessagesByTrade(System.DateTime startFrom, System.Nullable<System.DateTime> endTo, string id, string tradePlaceInn) {
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest();
            inValue.startFrom = startFrom;
            inValue.endTo = endTo;
            inValue.id = id;
            inValue.tradePlaceInn = tradePlaceInn;
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetTradeMessagesByTrade(inValue);
            return retVal.GetTradeMessagesByTradeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetTradeMessagesByTradeAsync(MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest request) {
            return base.Channel.GetTradeMessagesByTradeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeResponse> GetTradeMessagesByTradeAsync(System.DateTime startFrom, System.Nullable<System.DateTime> endTo, string id, string tradePlaceInn) {
            MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetTradeMessagesByTradeRequest();
            inValue.startFrom = startFrom;
            inValue.endTo = endTo;
            inValue.id = id;
            inValue.tradePlaceInn = tradePlaceInn;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetTradeMessagesByTradeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetArbitrManagerRegister(MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest request) {
            return base.Channel.GetArbitrManagerRegister(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.AMList GetArbitrManagerRegister(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest();
            inValue.date = date;
            MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetArbitrManagerRegister(inValue);
            return retVal.GetArbitrManagerRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetArbitrManagerRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest request) {
            return base.Channel.GetArbitrManagerRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterResponse> GetArbitrManagerRegisterAsync(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetArbitrManagerRegisterRequest();
            inValue.date = date;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetArbitrManagerRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetDebtorRegister(MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest request) {
            return base.Channel.GetDebtorRegister(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.DebtorList GetDebtorRegister(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest();
            inValue.date = date;
            MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetDebtorRegister(inValue);
            return retVal.GetDebtorRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetDebtorRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest request) {
            return base.Channel.GetDebtorRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterResponse> GetDebtorRegisterAsync(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetDebtorRegisterRequest();
            inValue.date = date;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetDebtorRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetCompanyTradeOrganizerRegister(MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest request) {
            return base.Channel.GetCompanyTradeOrganizerRegister(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.TradeOrganizerList GetCompanyTradeOrganizerRegister(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest();
            inValue.date = date;
            MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetCompanyTradeOrganizerRegister(inValue);
            return retVal.GetCompanyTradeOrganizerRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetCompanyTradeOrganizerRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest request) {
            return base.Channel.GetCompanyTradeOrganizerRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterResponse> GetCompanyTradeOrganizerRegisterAsync(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetCompanyTradeOrganizerRegisterRequest();
            inValue.date = date;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetCompanyTradeOrganizerRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse MessageServiceUsageExample.MessageServiceReference.IMessageService.GetSroRegister(MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest request) {
            return base.Channel.GetSroRegister(request);
        }
        
        public MessageServiceUsageExample.MessageServiceReference.SROList GetSroRegister(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest();
            inValue.date = date;
            MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse retVal = ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetSroRegister(inValue);
            return retVal.GetSroRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse> MessageServiceUsageExample.MessageServiceReference.IMessageService.GetSroRegisterAsync(MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest request) {
            return base.Channel.GetSroRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServiceUsageExample.MessageServiceReference.GetSroRegisterResponse> GetSroRegisterAsync(System.Nullable<System.DateTime> date) {
            MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest inValue = new MessageServiceUsageExample.MessageServiceReference.GetSroRegisterRequest();
            inValue.date = date;
            return ((MessageServiceUsageExample.MessageServiceReference.IMessageService)(this)).GetSroRegisterAsync(inValue);
        }
    }
}
